services:
  db:
    image: postgres:15
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Tell Adminer which server to connect to by default
      ADMINER_DEFAULT_SERVER: db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - python
      - -m
      - uvicorn
      - backend.server.main:app
      - --host
      - ${BACKEND_HOST}
      - --port
      - ${BACKEND_PORT}
      - --reload
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy


volumes:
  backend-db-data:
